//Author: Anani Assoutovi
//Professor: Dr. Benjamin Soibam
//Date: April 28th 2016

#include <iostream>
#include <random> 
#include <cstdlib>
#include <ctime>

void generateTicket(int lottery[], int size);
void generateBiasedTicket(int biasedLottery[], int size);
void getUserTicket(int UserTIcket[], int size);
void CompareTickets(int UserTicket[], int lotter[], int size);

//global variable 

const int size = 5;
int main()
{
	int lottery[size];
	int UserTicket[size];
	int RandomLottery[5], BiasedLottery[5];
	char choice;

	std::cout << "Do You Want To Generate Lottery Tickets? Enter Y or N ";
	std::cin >> choice;

	while (choice == 'Y' || choice == 'y')
	{
		//Generate Random Lottery Ticket
		//Generate Biased Lottery Ticket
		//Allow The User TO Enter Ticket

		//Compare User's Ticket And Random Lottery Ticket
		//Compare User's Ticket And Biased Lottery Ticket

		getUserTicket(UserTicket, size);
 
		generateTicket(RandomLottery, size);

		CompareTickets(UserTicket, RandomLottery, size);

		generateBiasedTicket(BiasedLottery, size);

		std::cout << "\nWould You Like To Re-Generate A New Lottery Ticket? Enter Y or N ";
		std::cin >> choice;
	}

	if (choice != 'Y' || choice != 'y')
	{
		exit(1);
	}
}

void generateTicket(int lottery[], int size)
{
	/*Generate a random number in the range of 0 through 9 for each element in the array*/
	srand((unsigned)time(0));
	std::cout << "\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" << std::endl;
	std::cout << "These Are The Computer Generated Numbers" << std::endl;
	for (int i = 0; i <= size-1; i++)
	{
		lottery[i] = (rand() % 9);
		std::cout << lottery[i] << " ";
	}
	std::cout << std::endl;
	std::cout << std::endl;
}

void generateBiasedTicket(int biasedLottery[], int size)
{
	/*Generate a random number in the range of 0 through  5 for each of the first 3
	elements in the array, and random number in the range of 0 through 9 for each
	of remaining elements in the array.*/
	int i, j;
	std::cout << "\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" << std::endl;
	std::cout << "This is the Biased Computer Generated Numbers" << std::endl;
	srand((unsigned)time(0));
	for (i = 0; i <3; i++)
	{
		biasedLottery[i] = (rand() % 5);
		std::cout << biasedLottery[i]<<" ";
	}
	for (j = 3; j <5; j++)
	{
		biasedLottery[j] = (rand() % 9);
		std::cout << biasedLottery[j]<<" ";
	}
	std::cout << std::endl;
}

void getUserTicket(int UserTicket[], int size)
{
	/*Asks the user to enter 5 numbers(each number in the range of 0 through 9) to represent
	the user's ticket number. The user's ticket should be stored in the array UserTicket.*/

	int choice, i;
	std::cout << "\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" << std::endl;
	std::cout << "Please Enter Your Five Digit Numbers: " << std::endl;
	std::cout << "Your Numbers Must Be In The Range Of 0 To 9: " << std::endl;
	for (i = 0; i < 5; i++)
	{
		std::cout << "Please Enter The " << i + 1 << " Of Your Five Numbers: ";
		std::cin >> choice;

		if (choice >= 0 && choice <=9)
		{
			UserTicket[i] = choice;
		}
		else
		{
			std::cerr << "Error, Please Try Again!!!"<<std::endl;
			choice = --i;
		}
	}
	std::cout << "\nThese Are The Numbers You Selected: ";
	for (int j = 0; j < 5; j++)
	{
		std::cout << UserTicket[j] << " ";
	}
	std::cout << std::endl;
}

void CompareTickets(int UserTicket[], int lottery[], int size)
{
	/*Compares the user's ticket (UserTicket) against the ticket generated by the computer (lottery)
	The function should display matched and unmatched numbers between the two tickets.*/

	int i = 0, matching = 0, unmatching = 0, temp=0;
	bool position[5];

	for (i = 0; i < size; i++)
	{
		position[i] = UserTicket[i] == lottery[i];

		if (position[i])
			matching++;
		else
			unmatching++;
	}
	std::cout << "# Of Matched Digits = "<<matching<<" At Position(s) ";
	
	for (int j = 0; j < size; j++)
		if(position[j])
			std::cout << j << ", ";

	std::cout << "\n# Of Unmatched Digits = " <<unmatching << " At Position(s) ";

	for (int j = 0; j < size; j++)
		if (!position[j])
			std::cout << j << ", ";
}
// 12